# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "com.macox.helloworld"
version = "0.0.1"
name = "Helloworld Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "com.macox.helloworld.stacks.alpine"
